### ISSUE TITLE
doctrine:migrations:migrate -> DoctrineCommandHelper.php:33 - PHP Fatal error:  Can't use method return value in write context

### ISSUE THREAD

**Issue by euronymous** [doctrine/DoctrineMigrationsBundle#122]
php app/console doctrine:migrations:migrate --env rc

PHP Fatal error:  Can't use method return value in write context in vendor/doctrine/doctrine-migrations-bundle/Doctrine/Bundle/MigrationsBundle/Command/Helper/DoctrineCommandHelper.php on line 33

**Comment by xabbuh** [comment]
@euronymous This has been fixed in the meantime. You can use the latest dev version for now.

**Comment by euronymous** [comment]
Thank you for info! :)

Anyway... I know that this isn't a DMB issue, but I can't update package via composer.
I've tried to remove DoctrMigrBndl, and run update again: 
(...)
  - Installing doctrine/doctrine-migrations-bundle (dev-master e33e071)
    Cloning e33e07137c43a492589e89d79d36807cbfcf28e0
But this is an old commit...
I've run composer clear-cache, cleared ~/composer/cache directory.
Nothing... :(

**Comment by euronymous** [comment]
Ohhh... packagist still have no info about new commit...
https://packagist.org/packages/doctrine/doctrine-migrations-bundle#dev-master

**Comment by fre5h** [comment]
Yes. Packagist didn't update hash of the last commit in dev-master, it is still two commits behind.
Maybe hook in repository for autoupdate is broken. Or... some problems with Packagist that's why it didn't update the last hash.
If you need doctrine migrations to work from dev-master right now, you can use hash of the last commit in your composer.json `dev-master#861d3564c03b3867845ffd87d9b19f49dc673c69`

**Comment by EricReiche** [comment]
thanks Artem

**Comment by euronymous** [comment]
Yeap :) that helps :) thanks!
