### ISSUE TITLE
Store migrations inside bundles and collect them from installed bundles

### ISSUE THREAD

**Issue by Koc** [doctrine/DoctrineMigrationsBundle#152]

**Comment by scaytrase** [comment]
As for me migrations are mostly the part of application, not the part of the bundle. Any application including any bundle can override some parts of this configuration (i.e Doctrine mappings) which leads to incorrect migrations in bundle for that particular applicaton.

I.e I can have a entity naming strategy which breaks your bundle migrations.

Until there is no abstraction layer for the migrations keeping migration at the bundle level should not be included into the base migration library.

**Comment by stof** [comment]
@scaytrase is right. The database is not under the control of the bundle, and migrations are tied to the database

**Comment by Koc** [comment]
What to do it we ship "vendor" bundle with database schema which reused beetween multiple apps?

**Comment by scaytrase** [comment]
@Koc  Looks like the point to invert the dependencies. Looks like you actually ship the core application which is extended by the end users?

**Comment by groganz** [comment]
Maybe what we implemented is what you are looking for? It's basically an extension of the DoctrineMigrationsBundle and allows you to store the migration files per bundle. By default, they'd be located in /Resources/update/schema.

Our bundle searches all installed packages for migrations files in that directory and then executes them with the DoctrineMigrationsBundle.

Check it out on GitHub for more details: https://github.com/CampaignChain/update

**Comment by garex** [comment]
@scaytrase Let's just replace term `database` in your message with `configuration`:

As for me **configuration** are mostly the part of application, not the part of the bundle. Any application including any bundle can override some parts of this configuration (i.e Doctrine mappings) which leads to incorrect **configurations** in bundle for that particular applicaton.

I.e I can have a entity naming strategy which breaks your bundle **configurations**.

Until there is no abstraction layer for the **configuration** keeping migration at the bundle level should not be included into the base migration library.

**Comment by garex** [comment]
DB data is not under bundle or any module control. But DB structure -- could be. Think of it as a configuration. In symfony world we have the ability to provide default config fo a bundle, change it from another bundle and finally update in app.

Same should be ok in any migrations lib.

Another example: Iterators. In simple case we have just dumb iterator. But someday we want to use recursive iterator or another one. To the iterator's user there is no difference regarding it's usage -- it just use it inside good old for, foreach, etc.

Currently phinx allows to use migrations from many places:

```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/{app,src/*Bundle,vendor/NameYou/*}/Migration
```

We can start from something similar.

**Comment by scaytrase** [comment]
@garex Not sure, what you are meaning. Even with this replacement this quotation is still applicable. End-user application can override the `configuration`, so you have to use `abstract` migrations, generated for certain **end-user** `configuration`.

Until you do so, any `configuration` change ([naming strategy](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/namingstrategy.html), [mapping](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/override-field-association-mappings-in-subclasses.html), etc) will **break** your provided migration.

Just break. Crash. Explode. Boom!

I understand, that feature **renders useful** for distribution purposes for things like plugin for CMS, in example. But in products like these users are usually limited to access DB configuration, or it has several simple options (i.e. just table prefix)

But in these cases you'd better wrap the logic with `plugin` meaning, not just `bundle`. I.e when disabling "plugin" you still should do **revert migrations**. Which is not really possible when bundle is already disabled.

**Comment by garex** [comment]
> Until you do so, any configuration change (naming strategy, mapping, etc) will break your provided migration.

In phinx world where you use API like `this.table(bla).addColumn(foo).save` it will not. Only in a world or raw SQL which is doctrine auto-migrations are currently.

But this should not be a blocker.

Regarding naming strategy. It's a tool for development and not for end-user of bundle. When I want to use some bundle, I dont' want to think about it's naming conventions. I want from it to just f...n work. It's a  black box for me.

Possibly I want to config in which DB/entity manager this bundle should create it's tables. Or which prefix/postfix it should use. SQL is parsable so this should not be a problem.

**Comment by scaytrase** [comment]
> When I want to use some bundle, I dont' want to think about it's naming conventions. I want from it to just f...n work. It's a black box for me.

And they just f...n work. If they are good. Utility bundles provide you with interfaces, implementations and some configuration options. They do not provide you data, nor they manage it.

But imagine we have FoS\UserBundle with migrations you describe.

> In phinx world where you use API like this.table(bla).addColumn(foo).save it will not. Only in a world or raw SQL which is doctrine auto-migrations are currently.

1. What happens if I have already have table `bla` managed outside this application (no mappings present for it)?
2. What happens if I **do not wnat** to use FoSUB User implementation and use my own (remeber the relations, FoSUB User should not stay as the table to be related in this case).
3. What happens if I choose to drop my own implementation and get back the FoSUB one after some years? How migrations will be performed?
4. What happens if I have some schema patches (i.e. additional constraints, indexes, etc)?
5. How do you write highly customized data migrations (i.e requiring things like raw SQL\DQL) when you do not know which of **your tables** are really present at the moment of migrations?

> Just break. Crash. Explode. Boom!
That's what I just want to say. For most ideas I can find a use case which will either break or not possible to implement without limitation of end user.

To stop this endless discussion, I'll just summarize my POV here:

1. The feature we speaking of is great. Seriously.
2. But not as part of `MigrationsBundle`. Even not as something that wraps it.
3. But as part of some `plugin`\`module` distribution system implemented ontop of the `doctrine/migrations` it would be great. But having a limited scope of applications though
4. Only sealed systems can benefit for that distribution systems, like CRM, CMS, etc

> It's a black box for me.

5. The whole application should be blackbox with small configuration possibilities to benefit, so you can't modify the structure without force

**Comment by garex** [comment]
> What happens if ...

You just shoud have a way to not run those migrations. It's a design decision and also should not be a blocker. You should have a choice. Currently there is no choice.

Phinx gives such choice by providing you "many places" migrations, whether doctrine bundle -- not.

Only doctrine migrations lib, as I understand, gives you some customization way through some finder, but it's not obvious.

**Comment by scaytrase** [comment]
> You just shoud have a way to not run those migrations

So you say you must mark migrations to apply. Most of time migrations run with CI\CD systems like phing, capistrano, bare jenkins builds, etc with `--no-interaction` flag. Reviewing **each** migration (which, as you say will come from maybe hundred of places) results in a long process, and really is not different from just **copying** the migrations you want to apply to the your single migrations folder from bundle (i.e `cp vendor/my/bundle/Migrations/* app/Migrations/`).

Also what happen that I remove your bundle? Who is responsible to perform `drop table` migration since no code present in application vendors?

I repeat, you are trying to delegate to this bundle the responsibilities it shouldn't do. The idea is great. But not here.

**Comment by garex** [comment]
To those who will come here from google.

Currently there is ugly way to run migrations from many bundles:

```
doctrine_migrations:
    dir_name:             '%kernel.root_dir%/../vendor/yourname'
    namespace:            YourName\Migrations

```

Bad here is that it will search recursively and all migrations must be in same namespace.

**Comment by garex** [comment]
> So you say you must mark migrations to apply.

Who tells  it should be manually? People invented configuration files for this case.

For example some bundle have policy to autoadd migrations ot the app. You link it up and it will proceed. But if you want to skip it -- you mark somewhere in config:

```yml
doctrine_migrations:
   compose:
       bundle_x:
          skip: true
```

Regarding removing bundle. It's not an issue of doctrine_migrations. It's an issue of symfony bundles system at all. But for this case there should be some command like `doctine:migrations:compose:deactivate_bundle bundle_x` which will do the work.

**Comment by scaytrase** [comment]
`bundle_x` can have multiple migrations. I do not want to skip them all. just certain entity (I've replaced it with my own). Or I've override the metadata and there is no more column `bla` in `bundle_x.my_entity`. I wan't to disable any migrations that manipulate it.Or I want to replace single migration with my own to save or transform my data.

Anyway I have to review *all the migrations* that comes from the bundles to not to lost my data by accident

> like `doctine:migrations:compose:deactivate_bundle bundle_x` which will do the work

Is totally not possible at the moment. There is no `bundle_x` on the server when CI\CD performs the installation of new application revision. If you perform manual update (`deactivate bundle_x -> git pull -> composer install`) - yes this is possible, but again, this makes you to know, which bundles you have to deactivate before proceeding the installation.

> It's an issue of symfony bundles system at all.

It's not an issue. It's a design, simple and easy. It's not the **plugins**, nor the **modules**.

**Comment by garex** [comment]
> It's not the plugins, nor the modules.

ORLY? ))

http://symfony.com/doc/current/bundles.html

> A bundle is similar to a plugin in other software, but even better. The key difference is that everything is a bundle in Symfony, including both the core framework functionality and the code written for your application.

**Comment by scaytrase** [comment]
It's still not saying it **is** the plugin, yes?

**Comment by garex** [comment]
Also it's not saying that's not plugin. Yes?

Similar is more yes than no. So I win here ))

By the way, I think I will see to the `phinx` side but with doctrine's `diff` command. It's not so hard to implement some `doctrine:migrations:diff:phinx` command.

**Comment by scaytrase** [comment]
tiger is similar to cat. both can do `purr.. purr..` but it is a bad idea to bring a tiger to your bed.

bundle is similar to plugin. but there is no ecosystem around them to make them work as you describe. 

Sure, you can implement any system you need (and @groganz had already linked one above), but I think you will either end in writing plugin management system I describe or non-reusable specific implementation. Otherwise it would be easy to break.

Ping me when you'll have something to view and we'll continue.

**Comment by scaytrase** [comment]
@nuxwin 

If your system is fully modular than you should already have some kind of a plugin (module) manager which is fully responsible in what happens during module installation, configuration, deconfiguration and uninstallation. And the module schema management in this case is the responsibility of this plugin manager, not an development-land code (libraries, etc), along with features like upgrading, rolling back plugins, config migrations, etc.

If your sustem is not really modular but a kind of precompiled application (i.e modules are composer hard dependencies) than this modules are part of your application and it's your application (developer) responsibility how to manage their configs, migrations, when to upgrade and how to provision

**Comment by scaytrase** [comment]
Btw, since year I can say that flex recipes may resolve this problem, using some post-install hooks like composer scripts, copying migrations from bundle to app, since flex is the tool that helps

>  (developer) responsibility how to manage their configs, migrations, when to upgrade and how to provision

**Comment by goetas** [comment]
implemented in https://github.com/doctrine/DoctrineMigrationsBundle/pull/278

**Comment by garex** [comment]
> implemented in #278

Are you sure? How will I be able to run migrations from other bundles? Pls provide examples.

**Comment by goetas** [comment]
if you look at the new configuration options (https://www.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/configuration.html#line-number-acfdff376cf63cdfc50b1c7b4f7898cdb72f5e1f-14) it is possible to define migrations in multiple namespaces and locations. In the next weeks, the alpha version will be released together with a tutorial on how to use this feature.

**Comment by malutanpetronel** [comment]
When it will be this realeased @goetas?

**Comment by goetas** [comment]
See https://github.com/doctrine/DoctrineMigrationsBundle/issues/321
