### ISSUE TITLE
Unit testing command project generate deprecated error

### ISSUE THREAD

**Issue by christophe-mailfert** [doctrine/DoctrineMigrationsBundle#221]
Hi there,

I'm currently migrate my project to symfony 4, but when i'm running unit test got some deprecated error message:

```
Auto-registration of the command "Doctrine\Bundle\MigrationsBundle\Command\MigrationsGenerateDoctrineCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead: 4x
    1x in CreateClientCommandTests::testCanCreateClient from App\Tests\Command
....
```

Here is my test testCanCreateClient:

```
$slugToAdd = uniqid();

        $kernel = $this->getKernel();
        $application = new Application($kernel);
        $container = $kernel->getContainer();

        $domainUrl = 'xxx.fr';

        $mockAws = $this->createMock('Aws\Route53\Route53Client');
        $mockAws->expects($this->once())->method('getCommand')->will($this->returnCallback(function ($name, $params) use ($slugToAdd, $domainUrl) {
            $this->assertEquals('changeResourceRecordSets', $name);
            $this->assertEquals('UPSERT', $params['ChangeBatch']['Changes'][0]['Action']);
            $this->assertEquals($slugToAdd.'.'.$domainUrl, $params['ChangeBatch']['Changes'][0]['ResourceRecordSet']['Name']);

            return $this->createMock('Aws\CommandInterface');
        }));
        $mockAws->expects($this->once())->method('execute');

        $mockEncoder = $this->createMock(UserPasswordEncoderInterface::class);
        $mockEncoder->expects($this->once())->method('encodePassword')->willReturn('test');

        $application->add(new CreateClientCommand(
            $this->container->get('doctrine.orm.entity_manager'),
            $this->container->get(UserManager::class),
            $mockAws,
            $mockEncoder,
            '',
            $domainUrl,
            '',
            ''
        ));

        $command = $application->find('xxx:client:create');
        $commandTester = new CommandTester($command);
        $commandTester->execute(array(
            'command'  => $command->getName(),
            'client.name' => $clientName = 'test',
            'client.subdomain' => $slugToAdd,
            'contact.first_name' => $firstName = 'test firstname',
            'contact.last_name' => $lastName = 'test lastname',
            'contact.email' => $email = 'email@test.com',
        ));
```

I think error append when i'm calling command with command tester.

Any idea ?

Thx a lot.

**Comment by arderyp** [comment]
I am getting these too, similar to this `DoctrineFixturesBundle` issue: https://github.com/doctrine/DoctrineFixturesBundle/issues/204

**Comment by jwage** [comment]
What version are you using? These commands are registered in the service container here https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/Resources/config/services.xml

**Comment by arderyp** [comment]
@jwage, I am using

- DoctrineMigrationsBundle: `1.3.1`
- DoctrineMigrations: `1.8.1`
- Doctrine: `2.6.1`
- Symfony: `3.4.11`

**Comment by arderyp** [comment]
hmmm, that didn't fix the problem.  Now I'm getting confused.  As far as I can tell, simply having the commands registered as services, as you mentioned @jwage, should be enough to stop this warning...

I will keep digging into it.  If anyone else has any ideas, please let me know.

**Comment by arderyp** [comment]
As it turns out, my warning are being thrown from tests that are very similar in structure to that originally reported by @christophe-mailfert above.  I tried my best to debug this further, but couln't really get anywhere.

**Comment by arderyp** [comment]
Since there is no traction here, and since this doesn't really appear to be a problem with `DoctrineMigrations` itself, I opened an issue on `symfony/symfony` to get more clarity on the subject:  https://github.com/symfony/symfony/issues/28121

**Comment by arderyp** [comment]
@christophe-mailfert, did you have any luck resolving this?

**Comment by christophe-mailfert** [comment]
As i remember, i do not have this error anymore but i don't remember how :D

Solution:
- Maybe passed on symfony 4.1 ans use self::$container

**Comment by arderyp** [comment]
thanks for the input @christophe-mailfert.  Maybe I should just stop worrying about it.  Further debugging suggests that the system doesn't just fall into the deprecated code block during testing, but also during cache clearing, application startup, running all custom commands, etc.  Basically, at bootstraping.  This makes sense, but it was causing major concern for me under the assumption that my application simply worldn't work (due to failed bootstrap) on 4.x because of this error.  Fingers crossed that it resolves itself.

**Comment by arderyp** [comment]
For anyone else experiencing this problem:

In moving to Symfony FLEX, my `composer.json` was no longer including `symfony/symfony`, but rather the explicit symfony components/packages (as outlined [here](https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex)). As it turns out, I did not explicitly require `"symfony/console": "^3.4",`, which was causing version`4.1` of this package to be installed (as it is required by some other symfony component, and was defaulting to the latest version, I suppose).  I wasn't explicitly requiring various other packages as well, so I think my system was running in kind of a half 3.4 half 4.1 state.  Once I fixed my `composer.json`, wiped out `vendor/` and re-ran `composer install`, the warnings went away.
