### ISSUE TITLE
show confirmation prompt after the SQL diff to be executed

### ISSUE THREAD

**Issue by mathroc** [doctrine/DoctrineMigrationsBundle#281]
When running the doctrine:migration:migrate command, it shows:

> WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)

and only once accepted, when actually doing the migration it prints the SQL

I'd like to have an option to see it before hand in order to know which migrations I'm allowing to run.
I don't know if this would be considered a BC break so maybe with a `--preview` option ?

ps: I know I can run the command with `--dry-run` but I'm usually too lazy to `ctrl+c` at the prompt, run the dry-run mode and start the real command again (and I guess I'm not the only one)

**Comment by alcaeus** [comment]
If we were to add this, we would always have to hide it between a command-line option (either a special `confirm-sql` option or through verbosity switches) because of the large amount of output it can generate. I'd like to avoid a third option that controls how migrations are run.

When running migrations, users can choose to have the SQL saved to a file instead of run (using the `--write-sql` option) or have it printed outright using the `--dry-run` option. Given those, I believe it's possible to update your tooling to achieve what you want to do. One option is to create a command that calls the `migrate` command with the `--dry-run` and `--no-interactive` options set, confirm that it should proceed with the migration, then call `migrate` again without `--dry-run` to run the migrations.

I'm closing this since we won't be implementing this, but thanks for your suggestion.
