### ISSUE TITLE
Implement auto down migrations

### ISSUE THREAD

**Issue by bOmBeLq** [doctrine/DoctrineMigrationsBundle#394]
So let's say I have 2 code bases:
v1.0 - contains 2 migration files
v1.1 - contains 3 migration files

Now let's say my prod instance is at v1.1, migrations already ran. And I need to roll back to v1.0. 

Problem: There is no simple way to automate this. I'd have to implement my own tool to compare migration files from v1.0 and v1.1 and rollback migrations missing in v1.0 and existing in v1.1.

Resolve option: What if during UP migration actual migration class code is saved into DB (we already have table just need to add extra field). Then when running migration on let's say v1.0 migrations would be able to roll back the ones missing in code but existing in DB. Might seem little hacky to story migration class code in DB but that would probably be only option to fully automate it. 

What do you think?

**Comment by goetas** [comment]
there is no reliable way to implement automatic migrations, independently if they are up or down. A bigger issue in a running database is also on how to migrate the data in the schema.

I would suggest you to have just a script that recreates the whole DB when you need to switch back and forth from a newer version to an older one.

There have been proposals in the past to remove completely the idea of having down migrations (https://github.com/doctrine/migrations/pull/162), just because they are hard, and in some situations they should not be done at all (of course it always depends)
